# Generated by Django 5.0.6 on 2024-07-01 15:59

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('maquina', models.CharField(max_length=100)),
                ('categoria', models.CharField(default='Operario', max_length=100)),
                ('conocimientos', models.CharField(default='null', max_length=100)),
                ('turno', models.CharField(max_length=20)),
                ('evento', models.BooleanField(default=False)),
                ('permutado', models.BooleanField(default=False)),
                ('fechaInicio', models.CharField(blank=True, db_column='fecha_inicio', max_length=10, null=True)),
                ('fechaBaja', models.CharField(blank=True, db_column='fecha_baja', max_length=10, null=True)),
                ('updateTurno', models.BooleanField(db_column='update_turno', default=False, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tarea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('fechacompleto', models.DateField(blank=True, null=True)),
                ('fecha_limite', models.DateField(blank=True, null=True)),
                ('fecha_actual', models.DateField(default=datetime.datetime.now)),
                ('completado', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Permutado',
            fields=[
                ('id_permutado', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_inicio', models.CharField(max_length=10, null=True)),
                ('fecha_fin', models.CharField(max_length=10, null=True)),
                ('tipo', models.CharField(max_length=250)),
                ('maquina', models.BooleanField(default=False)),
                ('auxiliar', models.CharField(max_length=250)),
                ('creador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permutados', to='blogapp.user')),
            ],
        ),
        migrations.CreateModel(
            name='Eventos',
            fields=[
                ('id_evento', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_inicio', models.CharField(max_length=10, null=True)),
                ('fecha_fin', models.CharField(max_length=10, null=True)),
                ('turno_actualizado', models.CharField(max_length=10)),
                ('observaciones', models.CharField(max_length=255)),
                ('creador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to='blogapp.user')),
            ],
        ),
    ]
