# Generated by Django 5.0.6 on 2024-07-02 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0002_user_expediente_incidencia_parte'),
    ]

    operations = [
        migrations.AddField(
            model_name='parte',
            name='fecha_reporte',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
