# Generated by Django 5.0.6 on 2024-07-12 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0005_alter_incidencia_fecha_incidencia_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incidencia',
            name='observaciones',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='parte',
            name='observacion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='parte',
            name='observacion_operario',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='parte',
            name='observacion_responsable',
            field=models.TextField(blank=True, null=True),
        ),
    ]
