# Generated by Django 5.0.6 on 2024-07-15 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0009_remove_eventos_id_orden'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventos',
            name='orden',
            field=models.IntegerField(null=True),
        ),
    ]
