# Generated by Django 5.0.7 on 2024-08-12 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0010_eventos_orden'),
    ]

    operations = [
        migrations.AddField(
            model_name='incidencia',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='incidencias/'),
        ),
    ]
