# Generated by Django 5.0.7 on 2024-09-03 10:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0011_incidencia_imagen'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='faltas',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Faltas',
            fields=[
                ('id_evento', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_inicio', models.CharField(max_length=10, null=True)),
                ('fecha_fin', models.CharField(max_length=10, null=True)),
                ('turno_actualizado', models.CharField(max_length=10)),
                ('observaciones', models.CharField(max_length=255)),
                ('orden', models.IntegerField(null=True)),
                ('creador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='falta', to='blogapp.user')),
            ],
        ),
    ]
